name: Send Today's PR and Issues

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:
jobs:
  send_email:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      TZ: Japan
    services:
      mysql:
        image: mysql:8.0-debian
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Set up credentials
        run: |
          mkdir -p config/credentials
          echo "${{ secrets.RAILS_MASTER_KEY }}" > config/master.key
          echo "${{ secrets.RAILS_TEST_KEY }}" > config/credentials/test.key
      - name: Set up database
        run: |
          cp config/database.yml.ci config/database.yml
          bin/rails db:create RAILS_ENV=test
          bin/rails db:migrate RAILS_ENV=test
      - name: Send Notification
        run: |
          bin/rails runner "EmailsController.new.send_notification"
        env:
          RAILS_ENV: test
