name: Send Today's PR and Issues

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0-debian
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Set up database
        run: |
          bin/rails db:create
          bin/rails db:schema:load

      - name: Set up credentials
        run: |
          mkdir -p config
          echo "${{ secrets.RAILS_MASTER_KEY }}" > config/master.key
          echo "${{ secrets.RAILS_CREDENTIALS }}" > config/credentials/development.key
      - name: Send Notification
        env:
          RAILS_ENV: development
        run: |
          bin/rails runner "EmailsController.new.send_notification"
